### ISSUE TITLE
Yes/No type not giving me a value input screen?

### ISSUE THREAD

**Issue by richardhoward77** [measure-2-improve/support#1]
##### What is the issue? 
I am unable to add an Actioned field with a True/False answer within the Activity module table.

##### What would you expect to happen?
I expect to select the type of Yes/No and then have the Value tab appear. 

##### What steps are needed to replicate the issue?
Add details here as steps in order to replicate, for example. 

1. Go to http://www.m2itest.co.uk/richard/home
2. log in
3. Select Administration
4. Select Modules
5. Edit Activity Module
6. Select Design
7. Add configure field
8. Type set to Yes/No
9. Enter in Name

##### What browser does the issue appear on?
Google Chrome

**Comment by Gillardo** [comment]
Can you please try this on the newly setup site.  I have fixed the issue of showing error messages for validation now, so this may help us narrow down the problem

**Comment by richardhoward77** [comment]
I have tried this again but under Company > Company Details and named it test. This again didn't work as above - I select Yes/No as type but didn't get a value tab? It let me save the module ok.Thanks

**Comment by Gillardo** [comment]
Maybe your misunderstanding, on a Yes/No field, you would not have a Values tab.  You should only see a screen like so

![image](https://cloud.githubusercontent.com/assets/7406381/15428593/2dc5c0ca-1e94-11e6-9d34-eb848777cc7c.png)

**Comment by Gillardo** [comment]
The values tab should only appear for Text fields were you have selected the option Use Values

**Comment by Gillardo** [comment]
Issue closed, feel free to reopen if i have missed something
