### ISSUE TITLE
Mouse Pointer

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#10]
##### What is the issue? 
Incorrect mouse icon

##### What would you expect to happen?
When hovering over the side menu, the mouse pointer shows the 'insert' icon.
It should be the 'pointer' icon.

##### What steps are needed to replicate the issue?
Hover over the side menu - see screen shot - if you hover over the 'company details' option then the 'insert' icon is displayed.

![image](https://cloud.githubusercontent.com/assets/16575012/15469388/ee6c755e-20e1-11e6-8087-58beadd9d9c1.png)

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
Big fixed now in latest version, will upload shortly
