### ISSUE TITLE
module fields with values not displaying answers

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#103]
Fields specified as having values.

When on an Input page - the field is displayed as a text box rather than as a combo box. 

This also happens if the field can have multiple values.

Chrome

**Comment by LeahPike** [comment]
I had a quick look, doesn't seem to handle it at all @Gillardo?

`<input class="form-control" *ngSwitchCase="'text'" [(ngModel)]="data[field.propertyName]" [required]="field.required" name="{{ field.propertyName }}" />`
