### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by LeahPike** [measure-2-improve/support#105]
Is there a date picker? I'm given a text box but it doesn't like my dates!

## Module Input
![image](https://cloud.githubusercontent.com/assets/6124100/18985638/b9e92b18-86f0-11e6-9bb4-8f3682053aed.png)

## Module Input Validation Error
![image](https://cloud.githubusercontent.com/assets/6124100/18985646/c566ebe2-86f0-11e6-88de-e5d7b74495fe.png)

## Module Admin Edit
![image](https://cloud.githubusercontent.com/assets/6124100/18985661/e74456fa-86f0-11e6-9b54-83671c823ab4.png)

**Comment by Gillardo** [comment]
Added one for the moment, but i dont like it, but for now it allows us to pick dates.  Will keep this issue open and when got bit more time, will create our own, just like before

**Comment by Gillardo** [comment]
Added this to scoring as well
