### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#109]
Setting up the Links do not seem to work - the Name gets overwritten with the link. The link can be any URL (not just within the site).

I think the font used in the footer is too big.

**Comment by Gillardo** [comment]
Observations.

```<a href="{{link.link}}" target="_blank">{{link.name}}</a>``` 
should be wrote as
```<a [href]="link.link" target="_blank">{{link.name}}</a>```
As you are binding to the value.

External links should always begin with http:// or https://.  This should be added as a validation rule on the server.

**Comment by LeahPike** [comment]
Totally haven't added validation rules, will do that today. I was thinking the same about the property name.

**Comment by LeahPike** [comment]
Everything done, awaiting an upload. 😃
