### ISSUE TITLE
Delete Company Error

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#11]
##### What is the issue? 
Error on deleting a module record

##### What would you expect to happen?
Module record should be deleted.

##### What steps are needed to replicate the issue?
I. Define a new module
2. Do NOT give yourself permissions on the new module
3. Add new record for module and get an error msg (I think it adds the record anyway)
4. Give yourself full permissions permissions for the new module
5. add a new record for the module
5. You now see records that were added in error as well as the correctly added record
6. Try and delete the duff module record - you get an error. 

Example in my database:
![image](https://cloud.githubusercontent.com/assets/16575012/15469764/412f02be-20e4-11e6-80ec-a7eb23eb53dc.png)

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
I cannot replicate this using the steps you provided.  Can you replicate it?

**Comment by Gillardo** [comment]
I have however found a bug where by you cant delete a module record via the grid, so this has been fixed
