### ISSUE TITLE
Add scorecard creates a template

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#111]
Adding a scorecard seems to create a partial copy of the Template selected in the template library!

Using my database
Add an eForm (scorecard) - pick NHT (I think the last one listed is the 'real' one)
The scorecard created does not have any measures - only a Finish button is displayed
A copy of the template selected is now in the template library

You cannot delete or edit this template as it is incomplete.

**Comment by Gillardo** [comment]
Fixed...upload shortly
