### ISSUE TITLE
Template definition - failing to save

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#113]
Adding a measure to a template.

2 variables - one a answer (radio button), the other text (multi line - 250 chars)

Falls over when saving.
<img width="1139" alt="screen shot 2016-10-03 at 10 58 44" src="https://cloud.githubusercontent.com/assets/16575012/19033885/9c24cb40-8958-11e6-90f1-86c37d94b4fd.png">
<img width="1159" alt="screen shot 2016-10-03 at 10 56 39" src="https://cloud.githubusercontent.com/assets/16575012/19033895/a4a2b8c2-8958-11e6-9f99-b5fc5afc2eeb.png">

**Comment by Gillardo** [comment]
Think this is now working...uploading shortly
