### ISSUE TITLE
Form control layouts

### ISSUE THREAD

**Issue by Gillardo** [measure-2-improve/support#114]
At current i believe we have used a standard of
```
    <div class="row form-group">
        <label class="col-sm-2 col-form-label">Primary</label>
        <div class="col-sm-10 col-md-7">
            <input class="form-control" />
            <span class="text-muted">
                What text should be displayed for titles and lists.
            </span>
        </div>
    </div>
```

This does not take up the full width, but looks ok on standard laptop.  For the moment i am proposing that we stick with this layout and update all the controls all at the same time, after we see what is the recommended column amounts for all devices (xs, sm, md, lg) then all screens will look the same, and we can easily update them all at the same time

**Comment by LeahPike** [comment]
I've used the following on the database page:

```
<div class="row form-group">
    <label class="col-sm-12 col-md-2 col-form-label">Admin Name</label>
    <div class="col-sm-12 col-md-10">
        <input class="form-control" required [(ngModel)]="database.adminName" name="adminName" placeholder="Enter an admin name..." [disabled]="!permission.update"/>
    </div>
</div>
```

When it hits the small size it puts the name above the field. Otherwise it uses 2 and 10 so it takes up the full width. The above would do 2 and 7, which isn't the full width on medium display sizes?
