### ISSUE TITLE
Template save button at measure level

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#115]
When editing a template - it is sensible to save your changes at regular intervals.

However, you are normally at a measure level and there is no save button there - you have to go back up to Template and save and then come back down to working at the measure level again.

Wondering if there was some sort of 'quick save' option possible?

**Comment by Gillardo** [comment]
No...its just with the limitations of the current system, saving was done on a per measure basis... There is no reason why you should have to save at regular intervals now, unless it is something you want to do... surely the (second) it takes to flip to template, to save, and go back again, isnt that bad??

**Comment by Gillardo** [comment]
especially if we compare speed to "current" system lol

**Comment by Don-Gaudoin** [comment]
I suppose it is just that it has been fragile and when you are entering long lists of answers and then find it falls over - it was getting painful. So i got in the habit of frequent saving!

Once it is stable, I suppose you do not need to save all the time.

**Comment by Gillardo** [comment]
I do understand that....but once stable...you could actually add a complete template very fast
