### ISSUE TITLE
Text variable set to multi line

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#120]
If I define a variable as 'text, set it to multi line and no max chars.

Says it has been saved, but if you try and add a scorecard it falls over.

Go back to template definition and it has not saved. Stays like this ...

<img width="700" alt="screen shot 2016-10-04 at 16 01 43" src="https://cloud.githubusercontent.com/assets/16575012/19079696/61a20704-8a4c-11e6-98a0-c5b8217e7173.png">

**Comment by Gillardo** [comment]
multiline and maxLength was not saving no update...This has now been fixed.

But....if you are trying to update an existing scorecard to match the template...this will not happen on all values in the template...I am happy to explain this to you over the phone if you want??

Basically....If by changing the value in a template "definition" can mean that you could edit the scorecard and thus change the value....this value is copied to the scorecard at the time of creation!
