### ISSUE TITLE
Option Buttons

### ISSUE THREAD

**Issue by LeahPike** [measure-2-improve/support#125]
Right aligned or not. Generate screenshots.

**Comment by LeahPike** [comment]
# Module Grid
### Center Aligned Buttons
![image](https://cloud.githubusercontent.com/assets/6124100/19110765/cf893e98-8af3-11e6-8e33-3132cf0fce87.png)

### Right Aligned Buttons
![image](https://cloud.githubusercontent.com/assets/6124100/19110811/10a5e2a0-8af4-11e6-9dbe-9b47c892e3ec.png)

### Right Aligned Buttons without Column Heading
![image](https://cloud.githubusercontent.com/assets/6124100/19110820/21dd9db0-8af4-11e6-82e7-2d4ed46b14b1.png)

# Admin Grid
### Center Aligned Buttons
![image](https://cloud.githubusercontent.com/assets/6124100/19110708/6800e8ca-8af3-11e6-8d7f-647a1a13e542.png)

### Right Aligned Buttons
![image](https://cloud.githubusercontent.com/assets/6124100/19110679/381bcdbe-8af3-11e6-9691-096596602a53.png)

### Right Aligned Buttons without Column Heading
![image](https://cloud.githubusercontent.com/assets/6124100/19110746/b24f2522-8af3-11e6-9288-1afa6adc4a9c.png)

**Comment by LeahPike** [comment]
@Don-Gaudoin @Gillardo 💭

**Comment by Gillardo** [comment]
I prefer the center aligned when you have the Option heading as the text and buttons align nicely.  But if you get rid of the header text, then right aligned looks fine.

I think right aligned with the header just looks weird

**Comment by Don-Gaudoin** [comment]
I agree that right aligned with no heading looks best.

**Comment by Gillardo** [comment]
module-data\grid.component.html, module-data\related-grid.component.html and cms\files.component.html....

Well volenteered @LeahPike  to do all the rest :)

**Comment by LeahPike** [comment]
Done. Awaiting Upload.
