### ISSUE TITLE
Reference fields in input pages

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#131]
Should not allow entry of 'reference' fields on add pages if the system is going to allocate a number automatically.

**Comment by Gillardo** [comment]
This isnt an issue that i can see??  I am guessing you have ticked Unique and entered a starting number for the reference??

**Comment by Don-Gaudoin** [comment]
Yes i set it to start at 100 - so the system is going to insert a reference number, therefore I should not be asked to input a reference number (pointless and going to cause confusion when it disregards what i enter).
