### ISSUE TITLE
Footer - support info

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#134]
Our company name (under m2i support ) should be referred to as "measure2improve" rather than "Measure 2 Improve"

<img width="519" alt="screen shot 2016-10-05 at 15 32 33" src="https://cloud.githubusercontent.com/assets/16575012/19117540/3f250fda-8b11-11e6-9985-142819571654.png">

**Comment by LeahPike** [comment]
Done, awaiting next upload.

**Comment by LeahPike** [comment]
Uploaded
