### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#142]
##### What is the issue? 
When I select to reset my password on Fusion, it doesn't tell me what the reset is for

##### What would you expect to happen?
I would like the Subject of the Email to say "Fusion [Database Name] Password Reset" if possible

##### What steps are needed to replicate the issue?
Add details here as steps in order to replicate, for example. 

1. Go to http://www.m2itest.co.uk/julie/home
2. Click "forgot your password"
3. Enter email address in Email field
4. Click Submit
5. Sample of email below;
![password reset](https://cloud.githubusercontent.com/assets/19469440/19156828/1aa73b5e-8bdb-11e6-824e-ccd9c9bb419f.JPG)

##### What browser does the issue appear on?
Outlook

**Comment by Gillardo** [comment]
As i said before, please ignore ALL password changing stuff as i am looking at changing this all
