### ISSUE TITLE
Template Folder

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#15]
##### What is the issue? 
Newly created Template folder not found

##### What would you expect to happen?
New folder to be displayed on left of screen

##### What steps are needed to replicate the issue?
1. Start with no Template folders
2. Click Organiser and create a new folder (I called it "Default")
3. Go back to Library tab - the new folder is not there

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
New folder not appearing on the Library tab, as only folders with reports display here.

**Comment by Gillardo** [comment]
If you try to add a new report, you will see you can select the new folder you have added.  Upon saving a report into this folder, and going to library, the new folder appears
