### ISSUE TITLE
Defining answers for a variable 

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#17]
##### What is the issue? 
Error on saving template definition

##### What would you expect to happen?
Should save

##### What steps are needed to replicate the issue?
1. Defined a Template with one section and one measure
2. The measure has 5 variables - all radio buttons with answers
3. Then try and define 5 answers for each variable - the answers are:
Very Dissatisfied (1)
Dissatisfied (2)
Neither Satisfied or Dissatisfied (3)
Satisfied (4)
Very Satisfied (5)

Tried doing just one set of answers and fails to save.

Seems to save if you do one answer at a time - and then save the template.

Also had a problem where I deleted the 'neither' answer and it deleted the 'satisfied' and 'very satisfied' answers.

##### What browser does the issue appear on?

chrome

**Comment by Gillardo** [comment]
Fixed in latest version, will upload shortly
