### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#18]
Password Reset link not directing to correct page (I have internet connection)

Link goes directly to;

![site unavailable](https://cloud.githubusercontent.com/assets/19469440/15573160/e0288e58-233c-11e6-8ca5-2796263704e4.JPG)

Browser: Google Chrome

**Comment by Gillardo** [comment]
Can you please send me the email you recieved?

**Comment by Gillardo** [comment]
This is now fixed
