### ISSUE TITLE
Authorisation on iPad

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#19]
##### What is the issue? 
Authorisation page repeatedly shown when using Template option

##### What would you expect to happen?
Only get the Authorisation page once

##### What steps are needed to replicate the issue?
If you use an iPad and logon and then try and use Templates option - takes you back to the Authorisation page. This repeats and you never get to the Templates page.

##### What browser does the issue appear on?
Safari on iPad.
Note this all works fine on Safari on a desktop.

**Comment by Gillardo** [comment]
I have now changed authorization throughout the system.  Please try this again as no popups are now used
