### ISSUE TITLE
Trigger - Add Action - Fields missing

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#20]
##### What is the issue? 
Cannot choose the field from record that triggered action

##### What would you expect to happen?
Select from all fields on module that triggered action

##### What steps are needed to replicate the issue?
Adding a trigger to automatically create a contact record when adding a new company
Cannot specify the Company to use on the Contact record.

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
Now fixed in latest version. Upload shortly
