### ISSUE TITLE
Yes/No field not showing when viewing it

### ISSUE THREAD

**Issue by richardhoward77** [measure-2-improve/support#21]
##### What is the issue? 
I have created a Contacts modules and within there a field called Active with a type of Yes/No. When I add or even edit a contacts records the tick box option clearly shows however when I go in to just view the record the field is blank?

##### What would you expect to happen?
I would expect the field to show a tick in a box or not depending on what I originally selected. 

##### What steps are needed to replicate the issue?
Add details here as steps in order to replicate, for example. 

1. Go to http://www.m2itest.co.uk/richard/
2. On the top menu bar select View, View Contacts
3. Click on Search
4. Select a contact entry for example Clive Illingworth (just click on his name to view record)
5. This then displays the contact record below:

![image](https://cloud.githubusercontent.com/assets/19348343/15742299/ea575c0a-28b5-11e6-9043-c24407e7f97d.png)

##### What browser does the issue appear on?

Chrome

**Comment by Gillardo** [comment]
Changed in latest version.  Will upload shortly
