### ISSUE TITLE
Invisible Buttons

### ISSUE THREAD

**Issue by Malpass91** [measure-2-improve/support#25]
Update on the issue posted in the Company - Add thread; it looks like ALL the buttons have gone invisible. They all work, but not seeing what I'm clicking on makes it a bit hard to do the right thing on the first try:

![image](https://cloud.githubusercontent.com/assets/19705791/15818724/dd5d5fc6-2bd6-11e6-8e1e-05e52194653e.png)

**Comment by Gillardo** [comment]
Mine seem to be there in black.  If you are using chrome, can you open the developer console, and while that is open refresh the page.  Doing this forces it to load from the server and not from cache.

Let me know

So you can see mine
![image](https://cloud.githubusercontent.com/assets/7406381/15821864/58a560b2-2bea-11e6-8c84-2ba2c4cc2470.png)

**Comment by Gillardo** [comment]
Closing as i guess this is now ok
