### ISSUE TITLE
Unable to add a field and use an delete field name

### ISSUE THREAD

**Issue by richardhoward77** [measure-2-improve/support#26]
##### What is the issue? 
Naming a field within a module with a name that already exists but was previously deleted from the module comes up with the following error:

![image](https://cloud.githubusercontent.com/assets/19348343/15850990/d4c27164-2c92-11e6-81de-9c1b7b95e4e4.png)

##### What would you expect to happen?
I would expect if you deleted a field say with a name of measure2improve then you should be able to re-add a field with the same name as it doesn't exist.

##### What steps are needed to replicate the issue?

1. Go to http://www.m2itest.co.uk/richard/home
2. Click on Admin
3. Go to Modules
4. Select Company 
5. Click on Edit
6. Within the existing Company Details group click on Add Field
7. Give the field name Measure2improve
8. Re-Save the module

##### What browser does the issue appear on?
Chrome Version 51.0.2704.79 m

**Comment by Gillardo** [comment]
In a word.  No.  Any item that is deleted, is never deleted in the current system, it is marked as deleted.  If you added a field already, deleted it, then surely you should re-instate the field if you are trying to add a field with the same name?

This goes all ALL items in the database, AtCalcs, Reports, Triggers, Alerts, Pages etc, nothing is ever deleted.

There will be a "cleanup" piece of code that deletes items that have been marked as deleted for X period of time, but that will happen later

**Comment by richardhoward77** [comment]
The field was deleted from one module as I didn't need it. I want to be able to add this to a different module and ideally give it the same name as I used before.

**Comment by Gillardo** [comment]
Upon checking inside your database, you already have a field called measure2improve against the module Training Records, which has been deleted.  This is why you are getting an error.  You have also deleted a column called measure2improve against your company module.  You have a further 2 fields that are not deleted called measure2improve against modules Department Details and Service Centre.

In light of this, there is no issue here.  If you want a field called measure2improve again the Company module, re-instate the deleted field.
