### ISSUE TITLE
Text Field with use values not updating when removed and resaved

### ISSUE THREAD

**Issue by richardhoward77** [measure-2-improve/support#27]
##### What is the issue? 
I have a Text field within a module that has been setup to use values with a pre-configured list. If I go into this field and remove the tick, save the module, log out of the site, log back in and then go back in that module the field it still has the use values selected.

##### What would you expect to happen?
I would expect any changes made would be retained as it appears to have saved correctly without any errors.

##### What steps are needed to replicate the issue?

1. Go to http://www.m2itest.co.uk/richard/home
2. Click on Admin
3. Go to Modules
4. Edit Training Records modules
5. Edit Testing Values Field
6. Save Module
7. Log out of site.
8. Log back in.
9. Go back into Modules
10. Edit Training Records modules
11. Go into Testing Values - Advanced.

##### What browser does the issue appear on?
Chrome 51.0.2704.84 m

**Comment by Gillardo** [comment]
The useValue tick box in for the UI only currently and allows you to setup values.  By unticking it, the values are not deleted.  You should delete the values on the values tab.

If everyone agrees that "unchecking" the use Values box should delete all values, this is fine, but if you uncheck it by accident, that will be your tough luck...

**Comment by Gillardo** [comment]
I have now updated the useValues checkbox and useSync checkbox to delete any values or sync fields against the field when unchecked
