### ISSUE TITLE
'Score' not working for me!

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#29]
##### What is the issue? 
I have added a template and the score tab doesnt work when clicked

##### What would you expect to happen?
I'd expect to open up the detailed questions 'bit' and answer them

##### What steps are needed to replicate the issue?
login to chris, 
click client home page and 
take the search for electronic form option. there is only one form - open it and click the score tab
nothing happens!

##### What browser does the issue appear on?
Google Chrome

**Comment by Gillardo** [comment]
Because you have a space in the name.  I have updated this and it will be uploaded shortly
