### ISSUE TITLE
Manually created Add Subcontractor page doesn't allow me to add new

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#31]
##### What is the issue? 
I created a new Add Subcontractor page - however the 'Add New' tab doesn't fire 
I also cannot now edit existing records - the Edit option fails to operate

##### What would you expect to happen?
I wanted to add a new record.
I wanted to edit an existing record

##### What steps are needed to replicate the issue?
login to chris
Client home page 
take either Add subcontractor, or View Subcontractor
click the 'Add New' tab

![image](https://cloud.githubusercontent.com/assets/19467251/15855110/96aa0d84-2ca5-11e6-9369-319cd623816f.png)

on the Add subcontractor page, click the edit button against an existing record. The record fails to open...

##### What browser does the issue appear on?
Google Chrome

**Comment by Gillardo** [comment]
You have deleted/updated pages for Subcontractor.  A module MUST have an Input, View and Search page.  If you delete the Add page, then you will not be able to add.

You have got a page called Add subcontractor, but as you can see below, this is actually being told, it is the Search page. I have changed the page to an Input type for you, and it is now working fine.

HOWEVER!

You have deleted your Search constractor page, so you will never be able to search for a subcontractor.  You can either restore the correct page, or you can add a new page and make sureyou set the module = subcontractor and the type to Search

![image](https://cloud.githubusercontent.com/assets/7406381/15855878/ffd56e08-2ca9-11e6-8b91-a58caa6eb402.png)
