### ISSUE TITLE
Greyed out Edit button is misleading

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#32]
##### What is the issue? 
Chris keeps not seeing and then seeing but thinking that the grey edit button is not accessible as in 'greyed out'

##### What would you expect to happen?
button not to be grey!

##### What steps are needed to replicate the issue?

![image](https://cloud.githubusercontent.com/assets/19467251/15855387/223944c2-2ca7-11e6-969d-409bc6be7e1b.png)

##### What browser does the issue appear on?
google Chrome

**Comment by Gillardo** [comment]
This button is a particular style in bootstrap and they keep updating it, for the moment i will leave this until bootstrap 4 below a release canditate.  If the problem persists, then we can update all secondary buttons (the style this button uses) to another style/color
