### ISSUE TITLE
Uploading Strap Image Not Working

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#33]
Uploading strap image (either option) after logging into my database is showing the following error using Chrome;

![image upload](https://cloud.githubusercontent.com/assets/19469440/15855359/fc28eabc-2ca6-11e6-8822-9b238afecde1.JPG)

**Comment by Gillardo** [comment]
Have you got popups blocked on your site?  For the moment you must add a rule to allow popups on your site.  When you click on someone that you have not got authorizing for, it popups for you to login.

**Comment by M2iJulieAnne** [comment]
Thanks Darren, yes I did have.  I've changed it so this is working now!
