### ISSUE TITLE
Module Print

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#39]
##### What is the issue? 
When I print from an added item such as after I have added a Company, the following text is on the PDF Print.  I doubt it will be required by Clients;

![print](https://cloud.githubusercontent.com/assets/19469440/15864479/3a456bfe-2ccf-11e6-8d26-db86a1489565.JPG)

##### What would you expect to happen?
I agree it would be good to have branding on there, however I think it should be "quieter" and at the bottom of the page.  Maybe say something like "Powered by m2i Fusion" then have our little logo, website address maybe?  One for Don to decide though!

##### What steps are needed to replicate the issue?
1. Login to my database
2. Click Company
3. Click "Add New" to add a new Company item
4. Click "Save"
4. Click "Print"

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
The module prints are under development and at the moment.  New tests will be added for this once the functionality has been decided and finalised . Ignore this for the moment
