### ISSUE TITLE
Home page change

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#40]
##### What is the issue? 
Remove the static wording section

##### What would you expect to happen?
simplify home page

##### What steps are needed to replicate the issue?
Not a problem but here is the section to remove

<img width="1156" alt="screen shot 2016-06-07 at 17 14 27" src="https://cloud.githubusercontent.com/assets/16575012/15865609/59fc5a58-2cd3-11e6-819a-b6837982e43c.png">

##### What browser does the issue appear on?
all

**Comment by LeahPike** [comment]
I've removed the text, I'll upload it in the morning at work :)

**Comment by LeahPike** [comment]
Uploaded :smile:
