### ISSUE TITLE
Multiple choice item in module stopped working

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#42]
##### What is the issue? 
when I add a new entry, the checkbox array doesnt appear (it did yesterday)
Save gives Invalid data message

##### What would you expect to happen?
I want to be able to set a series of checkboxes against the entry
and click save 

##### What steps are needed to replicate the issue?
login as Chris
Click Client Project Home
Click Add Site
add a site name and click save

The checkbox array against 'Subtype' doesnt appear!
The entry box for Company is unavailable to use
Save button gives invalid entry message
![image](https://cloud.githubusercontent.com/assets/19467251/15898797/81cfbaac-2d91-11e6-822f-d8e2bd19aa43.png)

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
Now working

![image](https://cloud.githubusercontent.com/assets/7406381/16005345/b09d5dbe-315e-11e6-8bde-e5d58c5096e0.png)
