### ISSUE TITLE
date/time definition

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#43]
##### What is the issue? 
Module change not saving

##### What would you expect to happen?
should save

##### What steps are needed to replicate the issue?
added a date/time field to a module and it saved.
then edited module and get following error

![screen shot 2016-06-09 at 16 00 40](https://cloud.githubusercontent.com/assets/16575012/15934578/fafe3370-2e5b-11e6-9f76-0ffa5a9c5b76.png)

##### What browser does the issue appear on?

chrome

**Comment by Gillardo** [comment]
What module did you add this to?

**Comment by Gillardo** [comment]
Fixed
