### ISSUE TITLE
Images > Add New

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#45]
##### What is the issue? 
When I try to upload an image to the Files area, it does not show that I have added it

##### What would you expect to happen?
Save the image and display it in the grid

##### What steps are needed to replicate the issue?
Add details here as steps in order to replicate, for example. 

1. Login
2. Click Admin
3. Click Files
4. Click Add NEw
5. Navigate using browser to locate file, click Open.

Nothing happens at this stage...

If I then reload the page, no image displays.

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
This works fine.  Did you reload the page and try this again to make sure you didnt have any javascript errors previously?  I sent you an email about this last week

**Comment by M2iJulieAnne** [comment]
This does seem to be working now.   Its a bit confusing though as there is no progress bar to show whether the upload is happening  Would it be possible to add something to show that?

**Comment by Gillardo** [comment]
Ju,  progress for all http requests is shown at the top of the window....

**Comment by M2iJulieAnne** [comment]
I can't see anything happening where the little blue bar should be.  Can you? Also, I noticed the Delete and Preview areas aren't active yet on an image, should they be?

![delete](https://cloud.githubusercontent.com/assets/19469440/16226411/35829806-37a3-11e6-9036-1f2c826790df.png)

**Comment by Gillardo** [comment]
Fixed.  You should now see a full file progress indicator when uploading files

**Comment by M2iJulieAnne** [comment]
Super!  All working now!
