### ISSUE TITLE
Page > Display

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#47]
##### What is the issue? 
When I add module content in the Display area, then try to save the module, I get this error;

![image](https://cloud.githubusercontent.com/assets/19469440/16048123/c03cb494-324a-11e6-8a21-c8903e4f0914.png)

Console says;
![console](https://cloud.githubusercontent.com/assets/19469440/16048344/9dae5422-324b-11e6-845b-0cc88952ec8b.JPG)

##### What would you expect to happen?
No error

##### What steps are needed to replicate the issue?
Add details here as steps in order to replicate, for example. 

1. Login
2. Click Admin
3. Click Pages
4. Highligh "company" page
5. Click Edit
6. Click Design
7. Enter some test test
8. Click Save

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
Please try again with no security changes

**Comment by M2iJulieAnne** [comment]
Tried and get this on Save;

![save](https://cloud.githubusercontent.com/assets/19469440/16225356/237cf44e-379e-11e6-8c19-93f785643786.png)

**Comment by Gillardo** [comment]
I have tried this in the new version (not yet uploaded) and it seems to work fine.  I will close this issue, as you can open a new issue if something happens when i upload the new version
