### ISSUE TITLE
Adding documents on an Item

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#49]
##### What is the issue? 
Unable to **add a new document** to an item (E.g Company)

##### What would you expect to happen?
See a **Document Add** button

![documents](https://cloud.githubusercontent.com/assets/19469440/16075455/ee8a201a-32e6-11e6-869b-726bca0fe475.JPG)

##### What steps are needed to replicate the issue?

1. Login
2. Click **Company** from top menu
3. Click on a Company record
4. Click **Company Documents** button
5. No Add button is displayed.  Attachments has been actived on **Company Master Module**

##### What browser does the issue appear on?

Chrome

**Comment by Gillardo** [comment]
Now fixed in latest version.  Being uploading shortly.  if you do not see the buttons change, then the change has not been uploaded
