### ISSUE TITLE
Activating Scoring causing error

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#50]
##### What is the issue? 
If I activate scoring on my **Company** module when no templates have been defined, then try to click on a company record to open it, I get an error message which says "an error has occurred".

![error 1](https://cloud.githubusercontent.com/assets/19469440/16075996/351d7a84-32e9-11e6-9e28-d9037ac9f3e1.JPG)

Console:
![console error 1](https://cloud.githubusercontent.com/assets/19469440/16076034/5a38754e-32e9-11e6-958b-d64e1655e661.JPG)

##### What would you expect to happen?
Wouldn't expect the error

##### What steps are needed to replicate the issue?

1. Login
2. Click Company from top menu
3. Click on a  Company record to open it
4. Error occurs

##### What browser does the issue appear on?

Chrome

**Comment by Gillardo** [comment]
Well... i dont code stupid lol.  You shouldnt turn on the scoring module all of a sudden.  Extensions are created to be turned on from the start.
This is because a scorecard requires a template, you have created companies that have no templates.

**Comment by M2iJulieAnne** [comment]
Could we have a message to advise we need to add a Template instead of the standard error?  Someone is bound to do it!
