### ISSUE TITLE
Template creation not saving - Text type measure

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#51]
##### What is the issue? 
Created a basic Text measure on a new template called **Template 1**, says "an error has occurred" on Save

##### What would you expect to happen?
The measure/ template to save

##### What steps are needed to replicate the issue?

1. Login
2. Click **Templates**
3. Click **Add New**

Settings in use are as follows;
![basic1](https://cloud.githubusercontent.com/assets/19469440/16076777/02dd71c4-32ed-11e6-99ef-6b68ed7e5f6b.JPG)

![scoring 1](https://cloud.githubusercontent.com/assets/19469440/16076768/f9a30d3a-32ec-11e6-91e2-259cd8328b18.png)

![design](https://cloud.githubusercontent.com/assets/19469440/16076932/b7bc7ab8-32ed-11e6-9572-1ebff5dccc5b.JPG)

![basic2](https://cloud.githubusercontent.com/assets/19469440/16076801/23438b24-32ed-11e6-976a-68157aeab4bb.JPG)

![variable1](https://cloud.githubusercontent.com/assets/19469440/16076822/3c6a7234-32ed-11e6-8cb2-d72fe8d430b6.JPG)

![Uploading result2.JPG…]()

![formula](https://cloud.githubusercontent.com/assets/19469440/16076831/4b24e5ca-32ed-11e6-9dbb-b7dbfc231590.JPG)

![error2](https://cloud.githubusercontent.com/assets/19469440/16076860/73079100-32ed-11e6-8aa1-6871449aad1d.JPG)

##### What browser does the issue appear on?

Chrome

**Comment by Gillardo** [comment]
Cannot replicate

**Comment by M2iJulieAnne** [comment]
Hi, since you've done that update, with the same settings above I get this;

![Uploading template save.png…]()

**Comment by Gillardo** [comment]
No screenshot attached....

**Comment by M2iJulieAnne** [comment]
Sorry, here tis!
![template save2](https://cloud.githubusercontent.com/assets/19469440/16261553/f82f2ebc-3863-11e6-94d9-ce9eb54801cb.png)

**Comment by Gillardo** [comment]
I have created this measure type in the new version and it works fine.  Will let you know once this is uploaded

**Comment by M2iJulieAnne** [comment]
Thanks.  Can we keep this open until I've re-tested it so I don't forget what I have to do on it?
