### ISSUE TITLE
Smart Date - Week

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#52]
##### What is the issue? 
When trying to set up week as a smart date, week is selecting Sunday as the start of the week and saturday as the end of the Week

##### What would you expect to happen?
Week to be from Monday 00.01 to Sunday 11.59

##### What steps are needed to replicate the issue?

1. Login
2. Click **Admin**
3. click **Smart Dates**
4. View Entry saved called **Week**

##### What browser does the issue appear on?

Chrome

**Comment by LeahPike** [comment]
@M2iJulieAnne can you confirm the behaviour of the current system? It you set up a week range what day does it start on?

**Comment by M2iJulieAnne** [comment]
When I add a new one after selecting "start today", it starts it from last Sunday....

**Comment by LeahPike** [comment]
I mean on econtrack.com :)

**Comment by M2iJulieAnne** [comment]
Ah, I will check and get back to you....

**Comment by M2iJulieAnne** [comment]
If I do it for "this week" it goes from Sunday 24th July - Saturday 30th July ... EEK!  Mostly that will be ok, as everything clients are adding is in working hours Mon-Fri, but that is definitely wrong!

**Comment by LeahPike** [comment]
In the new system you can probably offset the start and end dates by 1 to correct it. :)

**Comment by M2iJulieAnne** [comment]
probably, should it not be changed to the right thing though?
