### ISSUE TITLE
Relation field not showing previously set value

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#56]
##### What is the issue? 
When editing a 'contact' the company previously set is not visible

##### What would you expect to happen?
I'd expect to see the company currently set as the contacts 'home'

##### What steps are needed to replicate the issue?
login to chris
click home, search contact, click on a contact edit button

![image](https://cloud.githubusercontent.com/assets/19467251/16413740/bada02fe-3d2b-11e6-9185-f9cc18560b67.png)

##### What browser does the issue appear on?
google Chrome

**Comment by Gillardo** [comment]
I have tested this in the new angular2 version, and it seems to be working.  I will let you know when this has been uploaded

![image](https://cloud.githubusercontent.com/assets/7406381/18197796/0f384830-70f1-11e6-87d4-7ece9ee4f0c3.png)
