### ISSUE TITLE
[A]+[B] doesnt work!

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#57]
##### What is the issue? 
formulae definition of [A]+[B] causes crash on save of new eForm

##### What would you expect to happen?
to be able to save the eForm.

##### What steps are needed to replicate the issue?
login to Chris
click Home - Search eForm - Add New - fill out header info and click save - crash

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
Tried this in the new version, and [A]+[B] seems to work fine.  Will keep you posted when this update goes up
