### ISSUE TITLE
@calc definition doesnt offer result or variables from scoring extension

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#58]
##### What is the issue? 
@calc definition doesnt offer result or variables from scoring extension

##### What would you expect to happen?
@calc definition should offer result or variables from scoring extension to calculate with

##### What steps are needed to replicate the issue?
login to chris
add an @calc and attempt to do a rolling 12 calculation that sums the result from eForm 'staffing'

![image](https://cloud.githubusercontent.com/assets/19467251/16416680/5227e694-3d3b-11e6-9f42-e0c69db27909.png)

##### What browser does the issue appear on?

Chrome

**Comment by Gillardo** [comment]
This has been updated in angular2 so you can pick scoring extension fields.  Please note that you must pick the correct item in the first dropdown!  See attached example.

![image](https://cloud.githubusercontent.com/assets/7406381/17483312/68061a3c-5d7d-11e6-8ed3-768115e8b1cb.png)

![image](https://cloud.githubusercontent.com/assets/7406381/17483330/78ea9b48-5d7d-11e6-91e2-431d05be7713.png)

![image](https://cloud.githubusercontent.com/assets/7406381/17483337/858a9394-5d7d-11e6-842b-d05c1fca0ad2.png)
