### ISSUE TITLE
Module definition - constraint

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#59]
##### What is the issue? 
Editing module "Investigation" - make no changes and try to save module and it fails.

##### What would you expect to happen?
Save module

##### What steps are needed to replicate the issue?
Go to Module
Edit module Investigation
Save module without making any changes

##### What browser does the issue appear on?
Chrome

**Comment by Don-Gaudoin** [comment]
Darren

By a process of trial and error I have twigged that this is when you add a Bit field. Allows you to add one but when you edit the design (even if you make no changes), it falls over with this error.

**Comment by Gillardo** [comment]
Fixed this in angular2 version
