### ISSUE TITLE
Outstanding Development - Report Scheduling

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#6]
##### What is the issue? 
Need to be able to schedule reports to be generated and distributed via email.

##### What would you expect to happen?
Need to develop (would be nice to be able to define criteria for who gets the report and to be able to define the email that goes out).

**Comment by Gillardo** [comment]
Do we need to schedule a report anymore, or is a scheduled alert all you really need?  

> An alert is an email or text that gets sent out when particular criteria is met, and you can send it to a list of emails generated by another set of criteria.  


It seems to me that report scheduling becomes redundent if you can schedule an alert, because you can also select a report to be attached to an alert.  You also have options to change the email subject, and content of the email.

What do you guys think?

@measure-2-improve/support

**Comment by Don-Gaudoin** [comment]
Darren

You are right I think – Alerts would take care of it.

Regards

Don

**Comment by M2iJulieAnne** [comment]
I think this sounds good as long as we agree a sensible way of referencing/ tagging each alert so that support desk can locate them easily if there is a fault.

**Comment by Gillardo** [comment]
@measure-2-improve/support This feature is now complete.

Report scheduling is configurable by itself, you do not need to rely on alerts.  It all is configured from within the report.  You now have full control of the message that is sent, like you can on Alerts.

Typed email addresses have been dropped, and replaced with a criteria-like option.  This is how you will need to send all reports via schedules.  So if you want to send it to a random email address, you will either have to create a module, to hold a list of email addresses, or even add them in as a record against an existing Contact module.

**Comment by M2iJulieAnne** [comment]
Sounds good!

Question: If I change an email address in the system on a contact record, will that change be reflected in any report “schedule” recipients I have saved previously?

Regards

Ju

**Comment by Gillardo** [comment]
Yes it will

**Comment by M2iJulieAnne** [comment]
Super!
