### ISSUE TITLE
Error when saving an edited module - unknown cause

### ISSUE THREAD

**Issue by Malpass91** [measure-2-improve/support#61]
**What is the issue?** 

When attempting to edit a module, an error occurs when trying to save. 

![image](https://cloud.githubusercontent.com/assets/19705791/16447876/89a7c584-3de6-11e6-9b1b-322a7ad64a6f.png)

The console brings back the following, on each save attempt:
**Chrome:**
![image](https://cloud.githubusercontent.com/assets/19705791/16447212/5601db8c-3de3-11e6-84e8-548ed8dcb237.png)

**Firefox:** - One for line for each save attempt. FF Console says these are JS errors.
![image](https://cloud.githubusercontent.com/assets/19705791/16447584/260f3e18-3de5-11e6-9069-c0b22f25c11a.png)

To try and figure out the cause, I added a very basic module, with a text field. It worked. I then added another module, saved, and repeated until errors occurred. Number field worked, Firefox brought back errors on the Bit field, Chrome was okay with Bit, but had an error on Date.

I deleted the 'bad' field, but the errors persist on all modules. Returning to home screen, clearing cache and coming back to edit, has not solved the issue.

**What would you expect to happen?**

Modules to save without error.

**What steps are needed to replicate the issue?**

Attempt to edit any module on http://www.m2itest.co.uk/william/home

Feel free to add one and edit that.

**What browser does the issue appear on?**

- Chrome 51
- Firefox 47

**Comment by Malpass91** [comment]
*BUMP*

**Comment by Gillardo** [comment]
I have downloaded your database, upgraded it to the latest version and this seems to work fine.  I have entered every module and pressed save, and each one saves successfully...  I will let you know once this update is uploaded
