### ISSUE TITLE
Search module fails for me

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#62]
##### What is the issue? 
I logged into Don's database to review his incident log module. When I did Search - Incident Log I get an error and no results are shown (although there are incidents loaded)

##### What would you expect to happen?
I should be able to see existing records

##### What steps are needed to replicate the issue?
login to Don (using Don's email and password)
Click Search - Incident log
an error displays and then clears with no records shown

![image](https://cloud.githubusercontent.com/assets/19467251/16482355/485b7104-3ea7-11e6-8d71-be22e5b47c1f.png)

![image](https://cloud.githubusercontent.com/assets/19467251/16482499/e452a4ec-3ea7-11e6-897c-8ec2d2a6b2ee.png)

##### What browser does the issue appear on?

Chrome

**Comment by Gillardo** [comment]
I have downloaded Dons database, updated it to use angular2 and gone to this page, and it now works.  I will let you know when this version is uploaded.

![image](https://cloud.githubusercontent.com/assets/7406381/18198019/52a97eda-70f2-11e6-9a58-03b1c1715a10.png)
