### ISSUE TITLE
Report Folder set as default

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#63]
##### What is the issue? 
No "Root" default folder.   This is confusing if there are no instructions and just the "Add" button.   If you try to create a template without a folder the template will not save. 

##### What would you expect to happen?
Could we please assign a default "Root" folder to avoid this?

##### What steps are needed to replicate the issue?

1. Login
2. Create a template
3. Save Template
4. Click "Add" on save

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
Root folder is messy and ends up with reports being created everywhere.  
You can create a folder upon saving a template, like you can in the existing system.  Maybe a nice message will help here if you havent selected a folder?

**Comment by M2iJulieAnne** [comment]
Yes please, thanks!

**Comment by Gillardo** [comment]
The same code is used for atCalc, reports, workflow and templates....As you can see a message is displayed.  This has been implemented in the new angular2 version, which is not uploaded yet

![image](https://cloud.githubusercontent.com/assets/7406381/17483799/6a073c42-5d7f-11e6-978f-54ddbc888958.png)

**Comment by M2iJulieAnne** [comment]
Thanks!
