### ISSUE TITLE
Remember Me checkbox

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#65]
##### What is the issue? 
When I logout Remember me is not staying ticked from my previous login

##### What would you expect to happen?
If I had selected it on previous login, I would expect it to remain ticked. 

##### What steps are needed to replicate the issue?

1. Tick checkbox for "remember me"
2. Enter Login
3. Click Logout
3. Go to Login page

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
Try this on any web site...i have never seen this functionality.

**Comment by Gillardo** [comment]
We could tick it by default....  Not sure if this would cause other issues for people via security though

**Comment by M2iJulieAnne** [comment]
Ah.  If its doing what its supposed that's ok :-)
