### ISSUE TITLE
Contacts on a field

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#68]
##### What is the issue? 
When viewing contact first name and surname on a field, it would (imo) be easier to read if they were on one line instead of having the surname and first name on top of each other

##### What would you expect to happen?
Would be easier to read

##### What steps are needed to replicate the issue?
View contact via Scoring Wizard 

1. Login
2. Click "View Scorecard"
3. Click "Search"
4. Click "Add new" 
5. In the Scoring Group, in the  "Person" field type in "Murphy";

![person](https://cloud.githubusercontent.com/assets/19469440/17061818/48123aec-5028-11e6-8771-2c2434d2e773.png)

##### What browser does the issue appear on?

Chrome

**Comment by Gillardo** [comment]
You have set it up as a primary and secondary name.   If you want it on the first line, then you need to create a field called Full Name, which would consist of firstname + lastname, and then set that as your primary naming field.

**Comment by M2iJulieAnne** [comment]
Fab, thanks! Yes that's working now!
