### ISSUE TITLE
Formulas within a Datasheet will not cal with any null entries

### ISSUE THREAD

**Issue by richardhoward77** [measure-2-improve/support#73]
Logging as a result of Thursday 28th Workshop with DG & CB

When in Reports and creating a Datasheet if there are any null entries then if you have added in a formula it will calculate. If we take out the null entries this works as we would expect.

Screenshot to follow.....

**Comment by Gillardo** [comment]
This code uses the same code as the scoring wizard, and i have just fixed this in the new version.  If a null value is found, then a result of null is returned.  As i said this is in the new version only, and i will let you know once it has been uploaded
