### ISSUE TITLE
Error when saving a template

### ISSUE THREAD

**Issue by Malpass91** [measure-2-improve/support#76]
When attempting to save a template, I get an error. I have kept new templates close the default, filling in names, descriptions, incomplete and complete text.

Here are screenshots of the console:

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/19705791/17481962/88812154-5d77-11e6-8017-205e2f3febac.PNG)

Firefox:
![ff](https://cloud.githubusercontent.com/assets/19705791/17481975/9116d070-5d77-11e6-9a32-f7ff480fecc2.PNG)

**Comment by Malpass91** [comment]
UPDATE:

We have found this was caused by a folder not being selected when an attempt to save was made. If there's a way to get a prompt to say a folder must be selected in order to save, that'd help clear up a bit of confusion.

**Comment by Gillardo** [comment]
I have checked this in the new version, and the validation rule was missing on template, to make sure it is saved in a folder, thus the error message not being displayed.  Here is what it looks like now, when you do not select a folder when pressing save in the new version

![image](https://cloud.githubusercontent.com/assets/7406381/18431038/0fc5ceaa-78d3-11e6-98ae-2273adf506cf.png)
