### ISSUE TITLE
REQUEST - Add ability to copy measures in templates

### ISSUE THREAD

**Issue by Malpass91** [measure-2-improve/support#78]
##### What is the issue? 
The Fusion Template system has no feature for copying measures. Copying measures is a great time-saver in template building, and so it would be good to have on the new system too.

**Comment by Gillardo** [comment]
In the new version, i have added the option to copy a section within a template, and also copy a measure within a template

![image](https://cloud.githubusercontent.com/assets/7406381/18431369/894da0a8-78d4-11e6-8bdb-72f9f9130b98.png)

![image](https://cloud.githubusercontent.com/assets/7406381/18431384/95a72b9e-78d4-11e6-93f5-052dba9c446e.png)
