### ISSUE TITLE
Misplaced Link

### ISSUE THREAD

**Issue by georgia1702** [measure-2-improve/support#79]
##### What is the issue? 
When entering a link into a page content, the link appears out of the content page, please see below:
![image](https://cloud.githubusercontent.com/assets/19391519/18092370/f213a260-6ec3-11e6-82d1-f3d1d4f0c06a.png)

##### What would you expect to happen?
The link not to appear on other pages

##### What steps are needed to replicate the issue?
Add link into content section, move on to next page

##### What browser does the issue appear on?
Chrome

**Comment by georgia1702** [comment]
Side Note: It appears on every page

**Comment by Gillardo** [comment]
Fixed in new version
