### ISSUE TITLE
Tool Tips on View pages

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#8]
##### What is the issue? 
The 'tool tip' for a field not displayed. 

##### What would you expect to happen?
The Description associated with a field should be displayed as a 'tool tip' when hovering over the label or data field.

##### What steps are needed to replicate the issue?
1. Add a field for a module and enter a Description.
2. Display a View page for the module and hover over the label for the field above.

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
This has now been implemented in the new angular2 version

![image](https://cloud.githubusercontent.com/assets/7406381/18197471/3e5fc3d8-70ef-11e6-8037-39dc3d9f50a2.png)
