### ISSUE TITLE
database strap image

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#81]
##### What is the issue? 
adding a db strap image error

##### What would you expect to happen?
update successful

##### What steps are needed to replicate the issue?

1. go to database on admin menu.
2. added a strap image (attached) when pressing it triggers an error. I had opted for content width for the image.
![town_squat](https://cloud.githubusercontent.com/assets/16575012/18703021/1b8d2070-7fdc-11e6-99c8-0882627a2733.png)

##### What browser does the issue appear on?
chrome

**Comment by LeahPike** [comment]
I fixed this measure-2-improve/unite/issues#197
