### ISSUE TITLE
Add a Menu item

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#88]
The page drop down is truncated.

If you have already saved a page and then come back to edit it, even if you delete the page you saved before, it remembers and you cannot chose another page. You have to delete the menu item and add a new one.

This was using Chrome on an IOS tablet.

**Comment by LeahPike** [comment]
The search box doesn't seem to allow text input, includes PC version as well. I'll have a look.

**Comment by LeahPike** [comment]
![image](https://cloud.githubusercontent.com/assets/6124100/18787053/feb5a9ae-8198-11e6-8794-2a1c031b0f89.png)

Still need to fix this.
