### ISSUE TITLE
Database edit page - saving

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#89]
If you click Save - it does the save but there is no feedback to say it has done it. So you think it has not done anything.

**Comment by LeahPike** [comment]
A message is displayed at the top for a few seconds saying it has saved. You never get to see it though as you're scrolled to the bottom of the page to hit the save button.

In the previous "new" version it went back to a read-only page showing the database information. We could do that again. Or we could make it scroll to the top of the page when you save, or move the save message to the bottom? @Gillardo 💭 

![image](https://cloud.githubusercontent.com/assets/6124100/18786334/4473d122-8195-11e6-90e0-78d6e15f8c50.png)

**Comment by Don-Gaudoin** [comment]
I am happy with going back to the read only form or scrolling to the top of the page and displaying the message.



Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by Gillardo** [comment]
I think we should focus on the message, else we are never going to get this right, depending on the device used.  For example, if your in reporting, the message is fine at the top, but if you on a mobile device, i bet it aint.  If we focus the message, it will work on all devices plus you want to see what the message says
