### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#90]
Need to finish making this all modifiable.

1. The Email link does not get populated from the Admin email info.
2. I think we should get rid of the Request Call back option. Probably ought to have the m2i Support phone number and m2i email address as well as the admin phone and email.
3. I think we should allow the creation of 3 news items from the database page (Title and Short Story).
4. I think we should re Title "m2i Services" to "Links" and allow up to 6 links (Link Title and URL) 

Happy to consider alternative ideas.

**Comment by Don-Gaudoin** [comment]
I think we should get rid of the News Stories and replace it with "m2i Support" - where we would put the m2i telephone and email (as in Support - which we should re-title "Admin Support")

**Comment by LeahPike** [comment]
@Don-Gaudoin what is the the short story stuff? Could that be done via home page content?

**Comment by LeahPike** [comment]
Just need to add the ability to configure them via the database admin page. Might split the page up by tabs. Links, Admin etc..

Maybe look at splitting up the object like the settings version was, which is no longer used.

**Comment by Gillardo** [comment]
Database Links page should use the same standard "table" look, like everything else.
Database Links also has the "Removed" button using secondary color, where as all Remove/Delete buttons should use danger color

**Comment by LeahPike** [comment]
Will address inline editing with #126
