### ISSUE TITLE
Configure Search Grids

### ISSUE THREAD

**Issue by LeahPike** [measure-2-improve/support#94]
Should save the data in a cookie.

measure-2-improve/unite#194

**Comment by LeahPike** [comment]
It is not happy with re-ordering, doesn't remember the order.

If I re-order them and then delete one, it'll delete the wrong one!

@Gillardo :)

**Comment by Gillardo** [comment]
Fixed

**Comment by LeahPike** [comment]
Should it order by the fields chosen for the grid?

**Comment by Gillardo** [comment]
You mean should it order the results by the columns on the grid?  Maybe question for @Don-Gaudoin

**Comment by Don-Gaudoin** [comment]
It should order by the first column in the grid by default (ascending).

Then you can choose to order by any column by clicking on header etc.

Or have i misunderstood the question?

**Comment by LeahPike** [comment]
Yes, that is what I mean @Gillardo :)

So if I choose town as my 1st column it'll order the results by town.
