### ISSUE TITLE
Adding answers to a measure

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#98]
it would be nice if the new answer being added was set as 'active' by default - see screen shot

<img width="1147" alt="screen shot 2016-09-28 at 14 31 15" src="https://cloud.githubusercontent.com/assets/16575012/18915291/691bb2b4-8588-11e6-8cf4-b477a5c959af.png">

**Comment by Gillardo** [comment]
Done in next version, being uploaded shortly
