### ISSUE TITLE
Module Search

### ISSUE THREAD

**Issue by LeahPike** [measure-2-improve/support#99]
Might be nice if it was more evident that clicking on a row goes to the view screen.

Maybe change the cursor to show it is a "link".

![image](https://cloud.githubusercontent.com/assets/6124100/18915662/b42b7298-8589-11e6-9910-5f6afafe767d.png)

For some strange reason I always click on the edit button when I want to view it, because it is the first button and I don't read what it says ^^

@Don-Gaudoin @Gillardo 💭

**Comment by Gillardo** [comment]
I thought this was done, must be something has changed in the css since version 1

**Comment by Gillardo** [comment]
I thought it was in the bootstrap-override.scss file

**Comment by Don-Gaudoin** [comment]
I think that is a good idea.






Regards

Don

Donald Gaudoin | m2i | IT Director
Unit 17, Swallow Court, Devonshire Gate, Tiverton, EX16 7EJ | United Kingdom
Mobile: 07768 483667 | Office: 01884 841884 | Direct: 01934 710215
Email: donald.gaudoin@measure2improve.com<mailto:donald.gaudoin@measure2improve.com> |Web: www.measure2improve.com<http://www.measure2improve.com>

measure2improve is a trading name of Building Software Limited. Registered in England & Wales – Number  3117419
